spring:
  application:
    name: anime
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${JDBC_DRIVER_SOURCE}
    url: ${DB_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port:
    ${SERVER_PORT}
grpc:
  server:
    address: ${GRPC_SERVER_ADDRESS}
    port: ${GRPC_SERVER_PORT}

storage:
  bucket-name : ${STORAGE_BUCKET_NAME}
  namespace-name : ${STORAGE_NAMESPACE}
  configuration-file-path : ~/.oci/config
  profile : DEFAULT

kafka:
  bootstrap-servers: ${KAFKA_SERVER}
  schema-registry-url: http://localhost:8081
  consumer:
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    specific-avro-reader: true

